package com.simplesurvival.crates.service.chat

enum class ChatMessageKey
{
    // Manager
    CRATE_MANAGER_IDENTIFIER,
    CRATE_ITEM_NAME,
    CRATE_ITEM_LORE,
    CRATE_HOLOGRAM_LINE,
    CRATE_PREVIEW_REWARD_TEXT,
    CRATE_BROADCAST_MESSAGE,
    CRATE_PERMISSION_EDIT,

    REWARD_IDENTIFIER,
    REWARD_DISPLAY_NAME,
    REWARD_DISPLAY_LORE,
    REWARD_RESTRICTED_PERMISSION,

    REWARD_WIN_COMMAND,
    REWARD_WIN_COMMAND_EDIT,

    KEY_IDENTIFIER,
    KEY_ITEM_NAME,
    KEY_ITEM_LORE,
}
